[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = ["npm ci --include=dev"]

[phases.build]
cmds = [
  "npx prisma generate --schema=apps/api/prisma/schema.prisma",
  "npm run build:all"
]

[start]
cmd = "npm run start:prod"

[variables]
NODE_ENV = "production"