[build]
builder = "NIXPACKS"
watchPatterns = ["apps/**", "packages/**"]

[deploy]
startCommand = "npm run start:prod"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 30
region = "us-west1"

[build.environment]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"

[deploy.environment]
NODE_ENV = "production"
PORT = "3001"