[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run start:prod"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 30

[environments.production]
region = "eu-west1"  # Amsterdam - No Hyperliquid restrictions

[build.environment]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"

[deploy.environment]
NODE_ENV = "production"
PORT = "3001"