services:
  - type: web
    name: hyperliquid-bot-api
    runtime: node
    repo: https://github.com/YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
    rootDir: apps/api
    buildCommand: npm install && npm run build && npx prisma generate
    startCommand: npx prisma migrate deploy && npm start
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: hyperliquid-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: hyperliquid-redis
          property: connectionString
      - key: PORT
        value: 3001
      - key: FRONTEND_URL
        value: https://YOUR_DASHBOARD_URL.onrender.com
      - key: PYRAMID_STYLE
        value: aggressive
      - key: MAX_PYRAMID_LEVELS
        value: 4
      - key: MAX_ACCOUNT_EXPOSURE
        value: 0.55
      - key: ENABLE_PYRAMIDING
        value: true
      - key: ENABLE_BIDIRECTIONAL
        value: true
      # Add these via Render dashboard for security (NEVER commit):
      # - JWT_SECRET
      # - MASTER_ENCRYPTION_KEY
      # - WEBHOOK_SECRET
      # - WALLET_PRIVATE_KEY (your actual private key)
      # - HYPERLIQUID_API_URL (use https://api.hyperliquid-testnet.xyz for testnet)

databases:
  - name: hyperliquid-db
    plan: starter
    databaseName: hyperliquid
    user: hyperliquid

  - type: redis
    name: hyperliquid-redis
    plan: starter
    maxmemoryPolicy: allkeys-lru